<?php

namespace DoctrineProxies\__CG__\BulkImport\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Importer extends \BulkImport\Entity\Importer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'label', 'config', 'readerClass', 'readerConfig', 'processorClass', 'processorConfig', 'owner', 'imports'];
        }

        return ['__isInitialized__', 'id', 'label', 'config', 'readerClass', 'readerConfig', 'processorClass', 'processorConfig', 'owner', 'imports'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Importer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel(?string $label): \BulkImport\Entity\Importer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfig(array $config): \BulkImport\Entity\Importer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfig', [$config]);

        return parent::setConfig($config);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfig(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfig', []);

        return parent::getConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function setReaderClass(?string $readerClass): \BulkImport\Entity\Importer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReaderClass', [$readerClass]);

        return parent::setReaderClass($readerClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getReaderClass(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReaderClass', []);

        return parent::getReaderClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setReaderConfig(?array $readerConfig): \BulkImport\Entity\Importer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReaderConfig', [$readerConfig]);

        return parent::setReaderConfig($readerConfig);
    }

    /**
     * {@inheritDoc}
     */
    public function getReaderConfig(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReaderConfig', []);

        return parent::getReaderConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcessorClass(?string $processorClass): \BulkImport\Entity\Importer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcessorClass', [$processorClass]);

        return parent::setProcessorClass($processorClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessorClass(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessorClass', []);

        return parent::getProcessorClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcessorConfig(?array $processorConfig): \BulkImport\Entity\Importer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcessorConfig', [$processorConfig]);

        return parent::setProcessorConfig($processorConfig);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessorConfig(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessorConfig', []);

        return parent::getProcessorConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\Omeka\Entity\User $owner = NULL): \BulkImport\Entity\Importer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner(): ?\Omeka\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function getImports(): \Doctrine\Common\Collections\ArrayCollection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImports', []);

        return parent::getImports();
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceId', []);

        return parent::getResourceId();
    }

}
