<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImportRepresentation[] $imports
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-imports browse');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
?>

<?= $this->pageTitle($translate('Imports'), 1, $translate('Bulk import')) ?>

<div id="content">
    <h2><?= $escape($translate('Imports')) ?></h2>

    <?php if (count($imports)): ?>
        <?= $this->pagination() ?>
        <?= $this->partial('bulk/admin/import/import-table', ['imports' => $imports]) ?>
    <?php else: ?>
        <p><?= $escape($translate('No imports yet.')) ?></p>
    <?php endif; ?>
</div>
