<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImportRepresentation[] $imports
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-imports browse');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
?>

<?= $this->pageTitle($translate('Imports'), 1, $translate('Bulk import')) ?>

<div id="bulk-import">
    <h2><?= $escape($translate('Imports')) ?></h2>

    <?php if (count($imports)): ?>
        <?= $this->pagination() ?>
        <?php $this->trigger('view.browse.before'); ?>
        <?= $this->partial('bulk/admin/import/import-table', ['imports' => $imports]) ?>
        <?php $this->trigger('view.browse.after'); ?>
    <?php else: ?>
        <div class="no-resources">
            <p><?= $escape($translate('No imports yet.')) ?></p>
        </div>
    <?php endif; ?>
</div>
