<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImportRepresentation[] $imports
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
?>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $escape($translate('Importer')); ?></th>
            <th><?php echo $escape($translate('Status')); ?></th>
            <th><?php echo $escape($translate('Started')); ?></th>
            <th><?php echo $escape($translate('Completed')); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($imports as $import): ?>
            <tr>
                <td>
                    <?php echo $import->importer()->label(); ?>
                    <ul class="actions">
                        <?php if ($import->isInProgress()): ?>
                        <li><?php echo $hyperlink('', $url('admin/id', ['controller' => 'job', 'action' => 'stop', 'id' => $import->job()->id()]), [
                            'class' => 'fas fa-times-circle',
                            'title' => $translate('Stop'), // @translate
                        ]); ?></li>
                        <?php endif; ?>
                        <li><?php echo $hyperlink('', $this->url('admin/bulk/id', ['controller' => 'import', 'action' => 'show', 'id' => $import->id()]), [
                            'class' => 'fas fa-cogs',
                            'title' => $translate('See params'),
                        ]); ?></li>
                        <li><?php echo $hyperlink('', $this->url('admin/bulk/id', ['controller' => 'import', 'action' => 'logs', 'id' => $import->id()]), [
                            'class' => 'fas fa-list',
                            'title' => $translate('See logs'),
                        ]); ?></li>
                    </ul>
                </td>
                <td><?php echo $import->status(); ?></td>
                <td><?php if ($import->started()) echo $import->started()->format('Y-m-d H:i:s'); ?></td>
                <td><?php if ($import->ended()) echo $import->ended()->format('Y-m-d H:i:s'); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
