<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImportRepresentation[] $imports
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $escape($translate('Comment')) ?></th>
            <th><?= $escape($translate('Status')) ?></th>
            <th><?= $escape($translate('Started')) ?></th>
            <th><?= $escape($translate('Completed')) ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($imports as $import): ?>
            <tr>
                <td>
                    <?php $comment = $import->comment() ?>
                    <?php if ($comment): ?>
                    <?= $comment ?>
                    <span class="bulk-label-sub"><?= $import->importer()->label() ?></span>
                    <?php else: ?>
                    <?= $import->importer()->label() ?>
                    <?php endif; ?>
                    <ul class="actions">
                        <?php if ($import->isInProgress() || $import->isUndoInProgress()): ?>
                        <li><?= $hyperlink('', $url('admin/bulk/id', ['controller' => 'import', 'action' => 'stop', 'id' => $import->id()]), [
                            'class' => 'fas fa-times-circle',
                            'title' => $translate('Stop'), // @translate
                        ]) ?></li>
                        <?php endif; ?>
                        <?php if ($import->isUndoable()): ?>
                        <li><?= $hyperlink('', $url('admin/bulk/id', ['controller' => 'import', 'action' => 'undo', 'id' => $import->id()]), [
                            'class' => 'fas fa-undo',
                            'title' => $translate('Remove imported data'), // @translate
                        ]) ?></li>
                        <?php endif; ?>
                        <li><?= $hyperlink('', $this->url('admin/bulk/id', ['controller' => 'import', 'action' => 'show', 'id' => $import->id()]), [
                            'class' => 'fas fa-cogs',
                            'title' => $translate('See params'), // @translate
                        ]) ?></li>
                        <li><?= $hyperlink('', $this->url('admin/bulk/id', ['controller' => 'import', 'action' => 'logs', 'id' => $import->id()]), [
                            'class' => 'fas fa-list',
                            'title' => $translate('See logs'), // @translate
                        ]) ?></li>
                    </ul>
                </td>
                <?php if ($import->undoJob()): ?>
                <td><?= $translate($import->undoStatusLabel()) ?></td>
                <td>
                    <?php if ($import->started()) echo sprintf($translate('Import: %s'), $import->started()->format('Y-m-d H:i:s')); ?>
                    <br/>
                    <?php if ($import->undoStarted()) echo sprintf($translate('Undo: %s'), $import->undoStarted()->format('Y-m-d H:i:s')); ?>
                </td>
                <td>
                    <?php if ($import->ended()) echo $import->ended()->format('Y-m-d H:i:s'); ?>
                    <br/>
                    <?php if ($import->undoEnded()) echo $import->undoEnded()->format('Y-m-d H:i:s'); ?>
                </td>
                <?php else: ?>
                <td><?= $translate($import->statusLabel()) ?></td>
                <td><?php if ($import->started()) echo $import->started()->format('Y-m-d H:i:s'); ?></td>
                <td><?php if ($import->ended()) echo $import->ended()->format('Y-m-d H:i:s'); ?></td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
