<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Form\ImporterForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers edit');
$this->headLink()->appendStylesheet($assetUrl('css/bulk-import.css', 'BulkImport'));

$form->prepare();
?>

<?= $this->pageTitle($translate('Importer'), 1, $translate('Bulk Import')) ?>

<div id="content">
    <h2><?= $escape($translate('Create new importer')) ?></h2>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
