<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImporterRepresentation $importer
 * @var \BulkImport\Processor\Processor $processor
 * @var \Laminas\Form\Form $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));

$form->prepare();

$submit = $form->get('form_submit')->get('submit');
$submit->setAttribute('form', $form->getAttribute('id'));
$form->get('form_submit')->remove('submit');
?>

<?= $this->pageTitle($importer->label(), 1, $translate('Bulk import')) ?>

<?= $this->partial('bulk/admin/importer/menu-tab', ['importer' => $importer, 'current' => 'processor']) ?>

<div id="bulk-import">
    <h3><?= $escape(sprintf($translate('Processor: %s'), $processor->getLabel())) ?></h3>
    <p><?= $escape($translate('Fill the default values of the processor.')) ?></p>
    <?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form) ?>
    <?= $this->form()->closeTag() ?>
</div>

<div id="page-actions">
    <?= $this->formSubmit($submit) ?>
</div>
