<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImporterRepresentation $importer
 * @var \BulkImport\Reader\Reader $reader
 * @var \Laminas\Form\Form $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers edit');
$this->headLink()->appendStylesheet($assetUrl('css/bulk-import.css', 'BulkImport'));

$form->prepare();
?>

<?= $this->pageTitle($translate('Importer'), 1, $translate('Bulk import')) ?>

<div id="bulk-import">
    <h2><?= $escape($translate('Configure reader')) ?></h2>
    <h3><?= $escape(sprintf($translate('Importer: %s'), $importer->label())) ?></h3>
    <h3><?= $escape(sprintf($translate('Reader: %s'), $reader->getLabel())) ?></h3>
    <p><?= $escape($translate('Fill the default values of the reader.')) ?></p>
    <?php
    $submit = $form->get('importer_submit')->get('submit');
    $submit->setAttribute('form', $form->getAttribute('id'));
    $form->get('importer_submit')->remove('submit');
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>

<div id="page-actions">
    <?= $this->formButton($submit) ?>
</div>
