<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Interfaces\Reader $reader
 * @var \Laminas\Form\Form $form
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
$form->prepare();
?>

<?= $this->pageTitle($translate('Configure reader'), 1, $translate('Bulk import')) ?>

<div id="content">
    <h2><?= $escape($translate('Configure reader')); ?></h2>
    <h3><?= $escape(sprintf($translate('Reader: %s'), $reader->getLabel())) ?></h3>
    <p><?= $escape($translate('Fill the default values of the reader.')) ?></p>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
