<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImporterRepresentation $importer
 * @var \BulkImport\Form\ImporterDeleteForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers delete');
$this->headLink()->appendStylesheet($assetUrl('css/bulk-import.css', 'BulkImport'));

$form->prepare();
?>

<?= $this->pageTitle($translate('Importer'), 1, $translate('Bulk import')) ?>

<div id="bulk-import">
    <h2><?= $escape(sprintf($translate('Delete importer (%s)'), $importer->label())) ?></h2>
    <p><?= $escape($translate('Are you sure you want to delete this importer?')) ?></p>
    <?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form) ?>
    <?= $this->form()->closeTag() ?>
</div>
