<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Form\ImporterDeleteForm $form
 * @var \BulkImport\Api\Representation\ImporterRepresentation $entity
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers delete');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
$form->prepare();
?>

<?= $this->pageTitle($translate('Delete importer'), 1, $translate('Bulk import')) ?>

<div id="content">
    <h2><?= $escape(sprintf($translate('Delete importer (%s)'), $entity->label())) ?></h2>
    <p><?= $escape($translate('Are you sure you want to delete this importer ?')) ?></p>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
