<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImporterRepresentation $importer
 * @var \BulkImport\Form\ImporterForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers bulk-imports edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));

$form->prepare();
?>

<?= $this->pageTitle($translate('Importer'), 1, $translate('Bulk import')) ?>

<div id="bulk-import">
    <h2><?= $escape($translate('Edit importer')) ?></h2>
    <?php
    $submit = $form->get('importer_submit')->get('submit');
    $submit->setAttribute('form', $form->getAttribute('id'));
    $form->get('importer_submit')->remove('submit');
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>

<div id="page-actions">
    <?= $this->formSubmit($submit) ?>
</div>
