<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImporterRepresentation $importer
 * @var \BulkImport\Form\ImporterForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/bulk-import.css', 'BulkImport'));

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers bulk-imports edit');

$form->prepare();

$submit = $form->get('form_submit')->get('submit');
$submit->setAttribute('form', $form->getAttribute('id'));
$form->get('form_submit')->remove('submit');
?>

<?= $this->pageTitle($importer->label(), 1, $translate('Bulk import')) ?>

<?= $this->partial('bulk/admin/importer/menu-tab', ['importer' => $importer, 'current' => 'importer']) ?>

<div id="bulk-import">
    <p><?= $escape($translate('Set the default config of the importer, its reader and its processor, if any.')) ?></p>
    <?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form) ?>
    <?= $this->form()->closeTag() ?>
</div>

<div id="page-actions">
    <?= $this->formSubmit($submit) ?>
</div>
