<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImporterRepresentation[] $importers
 * @var \BulkImport\Api\Representation\ImportRepresentation[] $imports
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers bulk-imports browse');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
?>

<?= $this->pageTitle($translate('Bulk import'), 1, $translate('Bulk import')) ?>

<div id="page-actions">
<?php if (!empty($imports)): ?>
    <?= $hyperlink('See all imports', $url('admin/bulk/default', ['controller' => 'import', 'action' => 'browse'], true), ['class' => 'button']) ?>
<?php endif; ?>
</div>

<h2><?= $escape($translate('Available importers')) ?></h2>

<?php if (count($importers)): ?>
<table id="table-bulk-importer" class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $escape($translate('Name')) ?></th>
            <th><?= $escape($translate('Reader')) ?></th>
            <th><?= $escape($translate('Mapper')) ?></th>
            <th><?= $escape($translate('Processor')) ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($importers as $importer):
        $userIsAllowedUpdate = $importer->userIsAllowed('update');
        $userIsAllowedDelete = $importer->userIsAllowed('delete');
        ?>
        <tr>
            <td>
                <?= $hyperlink($importer->label(), $url('admin/bulk/id', ['controller' => 'importer', 'action' => 'start', 'id' => $importer->id()])) ?>
                <ul class="actions">
                    <li><?= $importer->link('', 'start', [
                        'class' => 'fas fa-cloud-upload-alt',
                        'title' => $translate('Import'),
                    ]); ?></li>
                    <?php if ($userIsAllowedUpdate): ?>
                    <li><?= $importer->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $translate('Edit'),
                    ]) ?></li>
                    <?php endif; ?>
                    <?php if ($userIsAllowedDelete): ?>
                    <li><?= $importer->link('', 'delete', [
                        'class' => 'o-icon-delete',
                        'title' => $translate('Delete'),
                    ]) ?>
                    <?php /*
                    echo $this->hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $importer->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $translate('Delete'),
                    ]) */ ?></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td>
                <?php $reader = $importer->reader(); ?>
                <?= $reader ? $reader->getLabel() : null; ?>
            </td>
            <td>
                <?= $escape($importer->bulkMapping() ? $importer->bulkMapping()->label() : str_replace(['/', ':'], [' / ', ': '], (string) $importer->mapper())) ?>
            </td>
            <td>
                <?php $processor = $importer->processor(); ?>
                <?= $processor ? $processor->getLabel() : null; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php endif; ?>

<?php if (!empty($imports)): ?>
    <h2><?= $escape($translate('Last imports')) ?></h2>
    <?= $this->partial('bulk/admin/import/import-table', ['imports' => $imports]) ?>
<?php endif; ?>
