<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImporterRepresentation[] $importers
 * @var \BulkImport\Api\Representation\ImportRepresentation[] $imports
 */

use BulkImport\Interfaces\Configurable as ConfigurableImport;

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers bulk-imports browse');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
?>

<?= $this->pageTitle($translate('Bulk import'), 1, $translate('Bulk import')) ?>

<h2><?= $escape($translate('Available importers')) ?></h2>
<?= $hyperlink('Add an importer', $this->url('admin/bulk/default', ['controller' => 'importer', 'action' => 'add'])) ?>

<?php if (count($importers)): ?>
<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $escape($translate('Name')) ?></th>
            <th><?= $escape($translate('Reader')) ?></th>
            <th><?= $escape($translate('Processor')) ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($importers as $importer): ?>
        <?php $userIsAllowedUpdate = $importer->userIsAllowed('update'); ?>
        <?php $userIsAllowedDelete = $importer->userIsAllowed('delete'); ?>
        <tr>
            <td>
                <?= $hyperlink($importer->label(), $this->url('admin/bulk/id', ['controller' => 'importer', 'action' => 'start', 'id' => $importer->id()])) ?>
                <ul class="actions">
                    <li><?= $importer->link('', 'start', [
                        'class' => 'fas fa-cloud-upload-alt',
                        'title' => $translate('Import'),
                    ]); ?></li>
                    <?php if ($userIsAllowedUpdate): ?>
                    <li><?= $importer->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $translate('Edit'),
                    ]) ?></li>
                    <?php endif; ?>
                    <?php if ($userIsAllowedDelete): ?>
                    <li><?= $importer->link('', 'delete', [
                        'class' => 'o-icon-delete',
                        'title' => $translate('Delete'),
                    ]); /*
                    echo $this->hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $importer->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $translate('Delete'),
                    ]); */ ?></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td>
                <?php $reader = $importer->reader(); ?>
                <?= $reader ? $reader->getLabel() : null; ?>
                <?php if ($reader instanceof ConfigurableImport): ?>
                    (<?= $hyperlink('Configure', $this->url('admin/bulk/id', ['controller' => 'importer', 'action' => 'configure-reader', 'id' => $importer->id()])) ?>)
                <?php endif; ?>
            </td>
            <td>
                <?php $processor = $importer->processor(); ?>
                <?= $processor ? $processor->getLabel() : null; ?>
                <?php if ($processor instanceof ConfigurableImport): ?>
                    (<?= $hyperlink('Configure', $this->url('admin/bulk/id', ['controller' => 'importer', 'action' => 'configure-processor', 'id' => $importer->id()])) ?>)
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php endif; ?>

<?php if (!empty($imports)): ?>
    <h2><?= $escape($translate('Last imports')) ?></h2>
    <?= $hyperlink('See all imports', $this->url('admin/bulk/default', ['controller' => 'import', 'action' => 'index'])) ?>
    <?= $this->partial('bulk/admin/import/import-table', ['imports' => $imports]) ?>
<?php endif; ?>
