<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\MappingRepresentation $bulkMapping
 * @var \BulkImport\Api\Representation\MappingRepresentation $resource
 * @var \BulkImport\Form\MappingDeleteForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-mappings delete');
$this->headLink()->appendStylesheet($assetUrl('css/bulk-import.css', 'BulkImport'));
$form->prepare();
?>

<?= $this->pageTitle($translate('Delete mapping'), 1, $translate('Bulk import')) ?>

<div id="bulk-import">
    <h2><?= $escape(sprintf($translate('Delete mapping (%s)'), $resource->label())) ?></h2>
    <p><?= $escape($translate('Are you sure you want to delete this mapping?')) ?></p>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
