<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\MappingRepresentation $bulkMapping
 * @var \BulkImport\Api\Representation\MappingRepresentation $resource
 * @var \BulkImport\Form\MappingForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-mappings edit');
$this->headLink()
    ->appendStylesheet($assetUrl('vendor/codemirror/lib/codemirror.css', 'BulkImport'))
    ->appendStylesheet($assetUrl('vendor/codemirror/addon/hint/show-hint.css', 'BulkImport'))
    ->appendStylesheet($assetUrl('css/bulk-import.css', 'BulkImport'));
$this->headScript()
    ->appendFile($assetUrl('vendor/codemirror/lib/codemirror.js', 'BulkImport'))
    ->appendFile($assetUrl('vendor/codemirror/addon/display/placeholder.js', 'BulkImport'))
    ->appendFile($assetUrl('vendor/codemirror/addon/hint/show-hint.js', 'BulkImport'))
    ->appendFile($assetUrl('vendor/codemirror/addon/hint/xml-hint.js', 'BulkImport'))
    ->appendFile($assetUrl('vendor/codemirror/mode/xml/xml.js', 'BulkImport'))
    ->appendFile($assetUrl('js/bulk-import-mapping.js', 'BulkImport'));

$form->prepare();
?>

<?= $this->pageTitle($translate('Edit mapping'), 1, $translate('Bulk import')) ?>

<div id="bulk-import">
    <h2><?= $escape($translate('Edit mapping')) ?></h2>
    <?php
    $submit = $form->get('submit');
    $submit->setAttribute('form', $form->getAttribute('id'));
    $form->remove('submit');
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>

<div id="page-actions">
    <?= $this->formSubmit($submit) ?>
</div>
