<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var bool $isBulkMapping
 * @var \BulkImport\Api\Representation\MappingRepresentation $bulkMapping
 * @var \BulkImport\Api\Representation\MappingRepresentation $ressource
 * @var string $label
 * @var string $content
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$urlHelper = $plugins->get('url');

$this->htmlElement('body')->appendAttribute('class', 'bulk-mappings show');
$this->headLink()
    ->appendStylesheet($assetUrl('vendor/codemirror/lib/codemirror.css', 'BulkImport'))
    ->appendStylesheet($assetUrl('vendor/codemirror/addon/hint/show-hint.css', 'BulkImport'))
    ->appendStylesheet($assetUrl('css/bulk-import.css', 'BulkImport'));
$this->headScript()
    ->appendFile($assetUrl('vendor/codemirror/lib/codemirror.js', 'BulkImport'))
    ->appendFile($assetUrl('vendor/codemirror/addon/display/placeholder.js', 'BulkImport'))
    ->appendFile($assetUrl('vendor/codemirror/addon/hint/show-hint.js', 'BulkImport'))
    ->appendFile($assetUrl('vendor/codemirror/addon/hint/xml-hint.js', 'BulkImport'))
    ->appendFile($assetUrl('vendor/codemirror/mode/xml/xml.js', 'BulkImport'))
    ->appendFile($assetUrl('js/bulk-import-mapping.js', 'BulkImport'));
?>

<?= $this->pageTitle($translate('Show mapping'), 1, $translate('Bulk import')) ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed(\BulkImport\Api\Adapter\MappingAdapter::class, 'create')): ?>
    <?php if (is_object($bulkMapping) && $bulkMapping->userIsAllowed('update')): ?>
    <?= $hyperlink($translate('Edit'), $urlHelper(null, ['action' => 'edit'], true), ['class' => 'button']) ?>
    <?php endif; ?>
    <?= $hyperlink($translate('Copy'), $urlHelper(null, ['action' => 'copy'], ['query' => $this->params()->fromQuery()], true), ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<div id="bulk-import">
    <h2 class="label"><?= $escape($label) ?></h2>
    <textarea name="o-bulk:mapping" id="o-bulk-mapping" rows="30" class="codemirror-code" rows="30"><?= $escape($content) ?></textarea>
</div>
